---
- hosts: 172.31.8.130
  become: yes
  tasks:
  - name:  i want to install git
    yum:
      name: git
      state: present
  - name: i want to install webserver on redat
    yum:
      name: httpd
      state: present