---
- hosts: webservers,
  become: yes
  tasks: 
  - name: i want to exectute linux commads
    command: hostname -f
    register:  myresult

  - name: i want disply above task result
    debug:
      msg: "{{myresult}}"

  - name:  i want to install  git
    apt: 
      name: git
      state: present
    when: myresult.stderr ==""


  - name: i want to instsll tree
    apt:
      name: tree
      state: present
    when: myresult.stderr !=""
