---
- hosts: webservers
  become: yes
  vars:
    mykey1: Devops
    mykey2: Aws
    mykey3: Linux
  tasks:
  - name:  i want to disply mykey1
    debug: 
      msg: "{{mykey1}}"
  - name: i want to disply mykey2
    debug:
      msg: "{{mykey2}}"
  - name: i want disply os
    debug:
      msg: "{{ansible_os_family}}"

  