---
- name: i want to download tomcat8 tar file
  get_url:
    url: https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.5/bin/apache-tomcat-8.5.5.tar.gz
    dest: /home/ubuntu/apache-tomcat-8.5.5.tar.gz
    force_basic_auth: yes
    